"""Material photos: a table for pictures of the bars and bundles.

A new table rather than a new document type. A document is one file per kind
per shipment and uploading another replaces it; photos are many per shipment
and none replaces another, so putting them in `documents` would have meant
the replace-on-same-type rule quietly destroying them.

WARNING about the downgrade: it drops the table, and with it every photo
record. The image files themselves stay in the storage directory as orphans,
so nothing is lost from disk, but the link between a photo and its shipment
is. Take a backup before downgrading past this point -- safe-deploy.sh does
that automatically.

Revision: 0004
Previous: 0003
Created:  2026-09-10 12:07:05.847673
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_shipment_id'), 'photos', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_shipment_id'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
