"""Container number and Bill of Lading number on a shipment.

Both nullable, because a shipment that predates this migration has neither
and there is nothing sensible to invent. Both are also genuinely optional
going forward: an LCL consignment may have no container of its own, and the
BL number does not exist until the carrier issues it, which is after the
vessel sails.

The downgrade drops the two columns and the values in them. Nothing else
depends on them, so nothing breaks -- but the numbers are gone, and they
came off a Bill of Lading somebody had to read. Back up first.

Revision: 0005
Previous: 0004
Created:  2026-09-10 12:23:53.431993
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('container_no', sa.String(length=20), nullable=True))
    op.add_column('shipments', sa.Column('bl_number', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'bl_number')
    op.drop_column('shipments', 'container_no')
    # ### end Alembic commands ###
